# Generated by Django 2.2.3 on 2019-10-16 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('colour', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('points', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
