# Generated by Django 2.2.3 on 2019-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='mascot',
            field=models.CharField(default='tbd', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='mascot_image',
            field=models.ImageField(default='', upload_to='houses/mascots/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
