# Generated by Django 2.0 on 2019-10-18 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20191016_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='academics',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='achievements',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='competitions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='misc',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='motto',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='sports',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
