# Generated by Django 2.0 on 2020-01-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_auto_20191018_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='mascot',
            field=models.CharField(max_length=8),
        ),
    ]
